server:
  port: 8082  
  tomcat:
    uri-encoding: utf-8  

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*.xml
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/northpark?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: caonima
    password: goulanzi
    
#    默认使用HikariDataSource 效率高的一批

#    使用druid配置
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid: 
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
#      filters: stat,wall
#      initial-size: 5
#      max-active: 30
#      max-pool-prepared-statement-per-connection-size: 50
#      max-wait: 60000
#      min-evictable-idle-time-millis: 300000
#      min-idle: 5
#      pool-prepared-statements: false
#      stat-view-servlet:
#        login-password: admin
#        login-username: admin
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      time-between-eviction-runs-millis: 60000
#      use-global-data-source-stat: true
#      validation-query: SELECT 1 FROM DUAL
   
    
  mvc:
    static-path-pattern: /static/**  
    view:
      prefix: classpath:/templates/  
      suffix: .html  
      
  #thymeleaf模板配置    
  thymeleaf:
    cache: false  
    enabled: true   
  #请求编码
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    
  #自动重启  
  devtools:
    restart:
      enabled: true 
      #排除
      #exclude: /
      
      
  #redis配置    
  redis:
   host: localhost
   port: 6379
   # 密码 没有则可以不填
   password: caonima
   # 如果使用的jedis 则将lettuce改成jedis即可
   lettuce:
     pool:
       # 最大活跃链接数 默认8
       max-active: 8
       # 最大空闲连接数 默认8
       max-idle: 8
       # 最小空闲连接数 默认0
       min-idle: 0    
         
  #日志打印  
logging:
  level:
    org.springframework.web: debug
    cn.northpark.mapper: debug  
    
    
    
